# Generated by Django 5.1.1 on 2025-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(choices=[('$', 'Günstig'), ('$$', 'Mittelpreisig'), ('$$$', 'Teuer')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='restaurants', to='restaurant.category')),
            ],
        ),
    ]
