# Generated by Django 5.1.7 on 2025-03-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(choices=[('$', 'Günstig'), ('$$', 'Mittelpreisig'), ('$$$', 'Teuer')], max_length=3),
        ),
    ]
